// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmBzp6b_HcAB-58w-pQqQC-_BBlpggKXc',
    appId: '1:985937699862:web:1d516b88f3f244566d4137',
    messagingSenderId: '985937699862',
    projectId: 'userdata-8832e',
    authDomain: 'userdata-8832e.firebaseapp.com',
    storageBucket: 'userdata-8832e.appspot.com',
    measurementId: 'G-3J1H3BV03K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApKAt2uWfQ8-AES_-YMGtNIhYnZzg6iNE',
    appId: '1:985937699862:android:08d6f1ec903e30986d4137',
    messagingSenderId: '985937699862',
    projectId: 'userdata-8832e',
    storageBucket: 'userdata-8832e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyEE1GpeiKTPrcD9EhRGhAIfvH3O8Kbxk',
    appId: '1:985937699862:ios:08ea5c6cc0d1e6cf6d4137',
    messagingSenderId: '985937699862',
    projectId: 'userdata-8832e',
    storageBucket: 'userdata-8832e.appspot.com',
    iosBundleId: 'com.example.personalinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyEE1GpeiKTPrcD9EhRGhAIfvH3O8Kbxk',
    appId: '1:985937699862:ios:08ea5c6cc0d1e6cf6d4137',
    messagingSenderId: '985937699862',
    projectId: 'userdata-8832e',
    storageBucket: 'userdata-8832e.appspot.com',
    iosBundleId: 'com.example.personalinfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmBzp6b_HcAB-58w-pQqQC-_BBlpggKXc',
    appId: '1:985937699862:web:87c7240da9ea206e6d4137',
    messagingSenderId: '985937699862',
    projectId: 'userdata-8832e',
    authDomain: 'userdata-8832e.firebaseapp.com',
    storageBucket: 'userdata-8832e.appspot.com',
    measurementId: 'G-VX2J30DW8P',
  );
}
